---
jobs:
- name: push-cf-cdn-service-broker
  plan:
  - get: broker-src
    trigger: true

  - task: run-tests
    file: broker-src/ci/run-tests.yml

  - task: create-db
    file: broker-src/ci/create-db.yml
    params:
      # Note: Name must match service name in manifest
      SERVICE_TYPE: aws-rds
      SERVICE_NAME: rds-cdn-broker
      SERVICE_PLAN: shared-psql
      <<: *cf-creds

  - put: broker-deploy
    params:
      path: broker-src
      manifest: broker-src/manifest-broker.yml
      environment_variables: &cfenv
        BROKER_USERNAME: {{cdn-broker-user}}
        BROKER_PASSWORD: {{cdn-broker-pass}}
        EMAIL: {{cdn-broker-email}}
        ACME_URL: {{cdn-broker-acme-url}}
        BUCKET: {{cdn-broker-bucket}}
        IAM_PATH_PREFIX: {{cdn-broker-iam-path-prefix}}
        AWS_ACCESS_KEY_ID: {{cdn-broker-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{cdn-broker-secret-access-key}}
        AWS_DEFAULT_REGION: {{cdn-broker-region}}

  - put: broker-deploy
    params:
      path: broker-src
      manifest: broker-src/manifest-cron.yml
      environment_variables:
        <<: *cfenv
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy cf-cdn-service-broker on {{cf-api-url}}
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed cf-cdn-service-broker on {{cf-api-url}}
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

  - task: update-broker
    file: broker-src/ci/update-broker.yml
    params:
      # Note: Name must match application name in manifest
      BROKER_NAME: cdn-broker
      AUTH_USER: {{cdn-broker-user}}
      AUTH_PASS: {{cdn-broker-pass}}
      PLAN_NAME: cdn-route
      <<: *cf-creds

resources:
- name: broker-src
  type: git
  source:
    uri: {{cf-cdn-broker-git-url}}
    branch: {{cf-cdn-broker-git-branch}}

- name: broker-deploy
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-deploy-username}}
    password: {{cf-deploy-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

cf-creds: &cf-creds
  CF_API_URL: {{cf-api-url}}
  CF_DEPLOY_USERNAME: {{cf-deploy-username}}
  CF_DEPLOY_PASSWORD: {{cf-deploy-password}}
  CF_ORGANIZATION: {{cf-organization}}
  CF_SPACE: {{cf-space}}
